### ISSUE TITLE
anyway to control the size of the icons?

### ISSUE THREAD

**Issue by coreybrett** [encukou/bytesize-to-jinja#1]
anyway to control the size of the icons?

**Comment by encukou** [comment]
Yes, using CSS.

See Bytesize Icons themselves for how to style them. Dan's [blog post](https://danklammer.com/articles/svg-stroke-ftw/) is useful.
I use something like:
```css
svg.icon {
    width: 1em;
    height: 1em;
    overflow: visible;
    stroke-width: 2.5px;
    stroke: currentColor;
    transform: translate(0px, 0.1em);  /* fine-tune the position to match my font */
    /* ... */
}
```
